INSERT INTO INVOICE (CLIENT,VAT_RATE, INVOICE_DATE) VALUES ('EOH', 14,'2020-01-01');
INSERT INTO INVOICE (CLIENT,VAT_RATE, INVOICE_DATE) VALUES ('Vodacom', 14, '2019-11-30');
INSERT INTO INVOICE (CLIENT,VAT_RATE, INVOICE_DATE) VALUES ('FNB', 14, '2019-12-01');


INSERT INTO LINE_ITEM  (QUANTITY,DESCRIPTION,UNIT_PRICE,INVOICE) VALUES (3, 'Services', 12.25,1);
INSERT INTO LINE_ITEM(QUANTITY,DESCRIPTION,UNIT_PRICE,INVOICE) VALUES (5, 'Laptops', 3499.99,1);
INSERT INTO LINE_ITEM(QUANTITY,DESCRIPTION,UNIT_PRICE,INVOICE) VALUES (7, 'support', 300,1);



INSERT INTO LINE_ITEM  (QUANTITY,DESCRIPTION,UNIT_PRICE,INVOICE) VALUES (3, 'Stationaries', 12.25,2);
INSERT INTO LINE_ITEM(QUANTITY,DESCRIPTION,UNIT_PRICE,INVOICE) VALUES (2, 'Supplies', 3499.99,2);
INSERT INTO LINE_ITEM(QUANTITY,DESCRIPTION,UNIT_PRICE,INVOICE) VALUES (7, 'Storage devices', 300,2);


INSERT INTO LINE_ITEM  (QUANTITY,DESCRIPTION,UNIT_PRICE,INVOICE) VALUES (1, 'Projectors', 12.25,3);
INSERT INTO LINE_ITEM(QUANTITY,DESCRIPTION,UNIT_PRICE,INVOICE) VALUES (4, 'Sound system', 3499.99,3);
INSERT INTO LINE_ITEM(QUANTITY,DESCRIPTION,UNIT_PRICE,INVOICE) VALUES (8, 'Training', 230,3);


