CREATE TABLE INVOICE (
  ID BIGINT(10) AUTO_INCREMENT PRIMARY KEY,
  CLIENT 	VARCHAR(20)  NOT NULL,
  VAT_RATE 	BIGINT(10) NOT NULL,
  INVOICE_DATE 	DATE NOT NULL
  
);

CREATE TABLE LINE_ITEM (
  ID BIGINT(10) AUTO_INCREMENT PRIMARY KEY,
  QUANTITY  BIGINT(10)  NOT NULL,
  DESCRIPTION 	VARCHAR(255) NOT NULL,
  UNIT_PRICE 	DECIMAL(18,2) NOT NULL,
  INVOICE BIGINT(10)NOT NULL,
  FOREIGN KEY(INVOICE) REFERENCES INVOICE(ID)
);